version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    depends_on:
      - db
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

  db:
        image: "postgres:13-alpine"
        container_name: db
        restart: always
        environment:
         - POSTGRES_USER=matchaadmin
         - POSTGRES_PASSWORD=matchapass
         - POSTGRES_DB=matchadb
  
  
        volumes:
         - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: